### ISSUE TITLE
Tesing endpoints from /docs/ shows "SvelteClient is not defined"

### ISSUE THREAD

**Issue by EdenKahane** [Bewinxed/svetch#1]
Hello,
I just implemented Svetch and it perfectly detect my endpoints. 
Unfortunately if I use the "Try" button under an endpoints, set a correct body and then click on the "Test" button : 
![image](https://github.com/Bewinxed/svetch/assets/108556499/2a3bd9c9-5a0e-4263-b800-7adfe5300967)

It shows "SvelteClient is not defined" 
And there seems to be a json error : 
![image](https://github.com/Bewinxed/svetch/assets/108556499/2e06ae4d-aef6-4ba4-bb48-27c3d6c0dbaa)

Here is my json generated when clicking on the "Try" button :
```json
{
	"email": "",
	"password": ""
}
```

Trying to do the same request on Insomnia works fine.

Is there a way to solve this ? 
Thanks !

**Comment by Bewinxed** [comment]
Heya, will fix this soon, but if you go to the /docs/+page.svelte, in the
script section, you will find the error in the svetch client import.

Cheers!

**Comment by EdenKahane** [comment]
Indeed, though each time I need to regenerate the doc, I need to add it again.
Thanks for your work !

**Comment by Bewinxed** [comment]
I'll fix it ASAP

**Comment by Bewinxed** [comment]
> Indeed, though each time I need to regenerate the doc, I need to add it again. Thanks for your work !

Hey! 1.0.48 fixes this,  try updating now!
