### ISSUE TITLE
Support for JSDocs on autogenerated docs

### ISSUE THREAD

**Issue by EdenKahane** [Bewinxed/svetch#2]
Hello,

I would like to use JSDocs comments to describe an endpoint (even though I'm using typescript for type definition). 
The readme seems to say it's possible, but I cannot understand how. 

Here is an example of a simple endpoint definition with the description `This is an endpoint description` with JSDocs, unfortunately, the description doesn't appears in the online /docs/ page. 

```ts
type UserLoginRequest = {
	email: string,
	password: string
}
/**
 * This is an endpoint description
 */
export const POST: RequestHandler = async ({ request }) => {
	const payload = await request.json() as UserLoginRequest
	return json({sucess: true});
};
```

Version:
- Svetch: 1.0.47
- Sveltekit: 2.0.4

Thanks for your help !

**Comment by Bewinxed** [comment]
Hello! Thanks for using the library, I'm on mobile rn but try to put the
jsdoc inside the code block and it will work.

So on the first line after =>

**Comment by EdenKahane** [comment]
Unfortunately,  I tried this and multiple other positions : 
```typescript
/**
 * This is an endpoint description 1
 */
export const POST: RequestHandler = 
/**
 * This is an endpoint description 2
 */
async ({ request }) => 
/**
 * This is an endpoint description 3
 */
{
/**
 * This is an endpoint description 4
 */
	
	const payload = await request.json() as UserLoginRequest
	return json({sucess: true});
};
```
None of them seems to work after regenerating the docs. I also tried each of them alone.

Thank you for making this library, it's very useful !

**Comment by Bewinxed** [comment]
> Unfortunately, I tried this and multiple other positions :
> 
> ```ts
> /**
>  * This is an endpoint description 1
>  */
> export const POST: RequestHandler = 
> /**
>  * This is an endpoint description 2
>  */
> async ({ request }) => 
> /**
>  * This is an endpoint description 3
>  */
> {
> /**
>  * This is an endpoint description 4
>  */
> 	
> 	const payload = await request.json() as UserLoginRequest
> 	return json({sucess: true});
> };
> ```
> 
> None of them seems to work after regenerating the docs. I also tried each of them alone.
> 
> Thank you for making this library, it's very useful !

Hey, just remembered, Put the jsdoc INSIDE the block, and in the first line.
and make sure to add the tag `@svetch` to the jsdoc

then it will work

in the generated schema.json, it will be in the 'description' field

example
```
export const POST: RequestHandler = async ({request, params, url}) => {
    /**
     * @svetch
     * @description {{name: string, age: number, email: string}}
     * The payload from the request, expected to be in the format: {name: string, age: number, email: string}
     */
    

    const premium = url.searchParams.get('premium')

    
    const payload = await request.json() as {name: string, age: number, email: string}

    const user = {id: 1, ...payload}

    return json(user);
};
```
adding it to the client, i might have time for it in the future, I think this whole lib needs a proper rewrite, and changing it to fit openapi spec, but i don't have resources atm.

this also makes it appear in the docs!

![image](https://github.com/Bewinxed/svetch/assets/9145989/0ac86f14-9c6e-4c3c-b5bb-90cb080ffbb9)

**Comment by EdenKahane** [comment]
Thank you a lot for this information.
Is there a documentation for this somewhere ? I looked on the README and on https://svetch-dev.vercel.app/ but didn't found anything about it.

An openapi support would be very good but I understand that this take a lot of time and work. Thank you for everything.

**Comment by Bewinxed** [comment]
I guess i forgot to include that bit :(

I would love to add openapi support soon need to clean up some stuff first.
