### ISSUE TITLE
Parameters shown as string instead of empty box in docs page

### ISSUE THREAD

**Issue by EdenKahane** [Bewinxed/svetch#4]
Hello,
When I set a path parameter : 
```typescript
export const PATCH: RequestHandler = async ({ request, url }) => {
	const index = url.searchParams.get('index') || '0'
	const payload = await request.json()
	return json({todo: true});
};
```
For some reason, in the /docs/ page, I don't have an empty box where I can input an exemple parameter to test, but just some sort of text under query : 
![image](https://github.com/Bewinxed/svetch/assets/108556499/85d34d95-bf8f-4dee-91fe-41590deb8006)

Using Svetch version 1.0.49

Thank for your help !

**Comment by Bewinxed** [comment]
Hello, I'm working on removing the docs page entirely and switch to Swagger/OpenAPI for docs.

It's in the latest version if you would like to try it.

**Comment by EdenKahane** [comment]
That's a very good idea ! I will try that next week :+1:

**Comment by Bewinxed** [comment]
Last version uses swagger, So this should be fixed 👍
